### ISSUE TITLE
List of Exercises per muscle group

### ISSUE THREAD

**Issue by esrefbozkurt** [esrefbozkurt/userStories#2]
## Value Proposition

**As a** ...user

**I need** ...see exercises for the chosen muscle group

**to be able to** ...see the exercises after clicking on muscle group and get back to the muscle groups page

## Description

Scribble / design or text
![image](https://user-images.githubusercontent.com/113592929/206981073-44293515-7dad-4f98-9a68-5297b2951765.png)

## Acceptance Criteria

- [ ] the name of the App is displayed in the heading 
- [ ] the "muscle group Exercises" header is displayed under the heading
- [ ] all exercises are displayed in boxes 
- [ ] every exercise box is displayed with a box  "description"
- [ ] a Backbutton should be displayed and by clicking it, the user gets back to the muscle groups page
- [ ] overflow is scrollable

## Tasks

- [ ] work on branch
- [ ] components MuscleGroups + Exercise + Backbutton
- [ ] (Storybook)
- [ ] testing
- [ ] routing from main muscle groups page to exercises page
- [ ] create Header for exercises with muscle group name 
- [ ] creating boxes of exercises by mapping through dummy data muscle groups
- [ ] create a box inside the exercise box with the content "description"
- [ ] create a Backbutton, which routs back to muscle groups page 
- [ ] basic styling components
